name: postgres
base: core18
version: "10"
summary: PostgreSQL
description: PostgreSQL

grade: stable
confinement: strict

passthrough:
  system-usernames:
    snap_daemon: shared
  hooks:
    install:
      environment:
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
      command-chain:
        - snap/command-chain/snapcraft-runner

apps:
  postgres:
    adapter: full
    command: usr/lib/postgresql/10/bin/postgres -D $SNAP_DATA/postgresql/10/main -c $CONFIG_ARG
    daemon: simple
    environment:
      CONFIG_ARG: config_file=$SNAP_DATA/etc/postgresql/10/main/postgresql.conf
    command-chain:
      - bin/gosu-snap_daemon.sh
      - bin/snapcraft-preload
    plugs:
      - network
      - network-bind
  psql:
    adapter: full
    command: usr/bin/psql
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    command-chain:
      - bin/psql-wrapper.sh
    plugs:
      - network

parts:
  # snapcraft preload is necessary to make postgres just use a different
  # lockfile location
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib
    stage-packages:
      - lib32stdc++6
  gosu:
    source: https://github.com/tianon/gosu.git
    plugin: go
    go-importpath: github.com/tianon/gosu
    build-environment:
      - CGO_ENABLED: "0"
  wrappers:
    plugin: dump
    source: .
    stage:
      - bin/
      - etc/
  postgres:
    plugin: nil
    stage-packages:
      - postgresql
      - postgresql-contrib
      - perl
