name: postgres
base: core18
version: "10"
summary: PostgreSQL
description: PostgreSQL

grade: stable
confinement: strict

passthrough:
  system-usernames:
    snap_daemon: shared
  hooks:
    install:
      environment:
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
      command-chain:
        - snap/command-chain/snapcraft-runner

apps:
  postgres:
    adapter: full
    command: usr/lib/postgresql/10/bin/postgres -D $SNAP_DATA/postgresql/10/main -c $CONFIG_ARG
    daemon: simple
    environment:
      CONFIG_ARG: config_file=$SNAP_DATA/etc/postgresql/10/main/postgresql.conf
    command-chain:
      - bin/gosu-snap_daemon.sh
      - bin/snapcraft-preload
    plugs:
      - network
      - network-bind
  psql:
    adapter: full
    command: usr/bin/psql
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PGHOST: $SNAP_COMMON/sockets
    command-chain:
      - bin/psql-wrapper.sh
      # createuser should be run as the snap_daemon user, which is the user
      # who is initially created as a role with postgres
      - bin/gosu-snap_daemon.sh
    plugs:
      - network
  psql-any:
    adapter: full
    command: usr/bin/psql
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PGHOST: $SNAP_COMMON/sockets
      PSQLRC: $SNAP_USER_COMMON/.psqlrc
    command-chain:
      - bin/psql-wrapper.sh
    plugs:
      - network
  createuser:
    adapter: full
    command: usr/bin/createuser
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PGHOST: $SNAP_COMMON/sockets
    command-chain:
      - bin/psql-wrapper.sh
      # createuser should be run as the snap_daemon user, which is the user
      # who is initially created as a role with postgres
      - bin/gosu-snap_daemon.sh
    plugs:
      - network
  createdb:
    adapter: full
    command: usr/bin/createdb
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PGHOST: $SNAP_COMMON/sockets
    command-chain:
      - bin/psql-wrapper.sh
      # createdb should be run as the snap_daemon user, which is the user
      # who is initially created as a role with postgres
      - bin/gosu-snap_daemon.sh
    plugs:
      - network

parts:
  # snapcraft preload is necessary to make postgres just use a different
  # lockfile location
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib
    stage-packages:
      - lib32stdc++6
  gosu:
    source: https://github.com/tianon/gosu.git
    plugin: go
    go-importpath: github.com/tianon/gosu
    build-environment:
      - CGO_ENABLED: "0"
  wrappers:
    plugin: dump
    source: .
    stage:
      - bin/
      - etc/
  postgres:
    plugin: nil
    override-build: |
      snapcraftctl build
      # the perl package for postgres hard-codes the bin dir as /usr/lib/postgresql
      # so we need to prepend that with /snap/postgres/current/ before it will
      # work
      if [ -z "$SNAPCRAFT_PROJECT_NAME" ]; then
        echo "SNAPCRAFT_PROJECT_NAME is undefined, snapcraft upstream change?"
        exit 1
      fi
      sed -i -e \
        's@our $binroot = \"/usr/lib/postgresql/\"@our $binroot = \"/snap/'$SNAPCRAFT_PROJECT_NAME'/current/usr/lib/postgresql/\";@' \
        $SNAPCRAFT_PART_INSTALL/usr/share/perl5/PgCommon.pm
    stage-packages:
      - postgresql
      - postgresql-contrib
      - postgresql-client
      - perl
